22:06:03.166 [http-nio-9999-exec-9] ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.io.FileNotFoundException: logs\center\data_sync-info.2020-05-14.log (系统找不到指定的文件。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.ntu.center.controller.LogInfoController.getLogInfo(LogInfoController.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
23:36:05.319 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: nested exception is org.apache.ibatis.binding.BindingException: Parameter 'nodeName' not found. Available parameters are [infoId, infoType, infoNode, param3, param1, param2]
23:36:27.396 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: nested exception is org.apache.ibatis.binding.BindingException: Parameter 'nodeName' not found. Available parameters are [infoId, infoType, infoNode, param3, param1, param2]
23:37:11.701 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'node_name' in 'where clause'
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select * from data_sync where info_id = ? and info_type = ? and node_name = ?
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'node_name' in 'where clause'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'node_name' in 'where clause'
23:37:22.103 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'node_name' in 'where clause'
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select * from data_sync where info_id = ? and info_type = ? and node_name = ?
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'node_name' in 'where clause'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'node_name' in 'where clause'
23:37:33.126 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'node_name' in 'where clause'
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select * from data_sync where info_id = ? and info_type = ? and node_name = ?
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'node_name' in 'where clause'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'node_name' in 'where clause'
23:37:44.156 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'node_name' in 'where clause'
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select * from data_sync where info_id = ? and info_type = ? and node_name = ?
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'node_name' in 'where clause'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'node_name' in 'where clause'
23:37:55.178 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'node_name' in 'where clause'
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select * from data_sync where info_id = ? and info_type = ? and node_name = ?
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'node_name' in 'where clause'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'node_name' in 'where clause'
23:38:28.982 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'sync_status' in 'class com.ntu.common.model.po.DataSync'
23:38:50.539 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'sync_status' in 'class com.ntu.common.model.po.DataSync'
23:39:12.633 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'sync_status' in 'class com.ntu.common.model.po.DataSync'
23:39:56.931 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into data_sync(info_id, info_type, info_node, sync_type, sync_status, success_time, fail_time, fail_count, sync_msg)         value(?,?,?,?,?,?,?,?,?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
; Column 'sync_type' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
23:40:18.327 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into data_sync(info_id, info_type, info_node, sync_type, sync_status, success_time, fail_time, fail_count, sync_msg)         value(?,?,?,?,?,?,?,?,?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
; Column 'sync_type' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
23:40:40.476 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into data_sync(info_id, info_type, info_node, sync_type, sync_status, success_time, fail_time, fail_count, sync_msg)         value(?,?,?,?,?,?,?,?,?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
; Column 'sync_type' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
23:41:02.506 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into data_sync(info_id, info_type, info_node, sync_type, sync_status, success_time, fail_time, fail_count, sync_msg)         value(?,?,?,?,?,?,?,?,?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
; Column 'sync_type' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
23:41:24.546 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into data_sync(info_id, info_type, info_node, sync_type, sync_status, success_time, fail_time, fail_count, sync_msg)         value(?,?,?,?,?,?,?,?,?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
; Column 'sync_type' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
23:42:20.863 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into data_sync(info_id, info_type, info_node, sync_type, sync_status, success_time, fail_time, fail_count, sync_msg)         value(?,?,?,?,?,?,?,?,?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
; Column 'sync_type' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
23:42:41.285 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into data_sync(info_id, info_type, info_node, sync_type, sync_status, success_time, fail_time, fail_count, sync_msg)         value(?,?,?,?,?,?,?,?,?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
; Column 'sync_type' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
23:42:52.319 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into data_sync(info_id, info_type, info_node, sync_type, sync_status, success_time, fail_time, fail_count, sync_msg)         value(?,?,?,?,?,?,?,?,?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
; Column 'sync_type' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
23:43:03.336 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into data_sync(info_id, info_type, info_node, sync_type, sync_status, success_time, fail_time, fail_count, sync_msg)         value(?,?,?,?,?,?,?,?,?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
; Column 'sync_type' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
23:49:16.746 [Timer-0] ERROR org.eclipse.paho.client.mqttv3.internal.ClientState - center: Timed out as no write activity, keepAlive=30,000 lastOutboundActivity=1,589,643,995,918 lastInboundActivity=1,589,644,023,819 time=1,589,644,156,742 lastPing=1,589,643,995,919
23:49:16.932 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into data_sync(info_id, info_type, info_node, sync_type, sync_status, success_time, fail_time, fail_count, sync_msg)         value(?,?,?,?,?,?,?,?,?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
; Column 'sync_type' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
23:51:22.316 [Timer-1] ERROR org.eclipse.paho.client.mqttv3.internal.ClientState - center: Timed out as no write activity, keepAlive=30,000 lastOutboundActivity=1,589,644,162,063 lastInboundActivity=1,589,644,166,042 time=1,589,644,282,315 lastPing=1,589,643,995,919
23:51:22.430 [MQTT Call: center] ERROR com.ntu.center.sync.CenterDataReceiver - cj_node 节点的 BOX_SENSOR 表中的 DataSync(infoId=1, infoType=B, syncType=1, syncStatus=1, successTime=null, failTime=null, failCount=0, syncMsg=null, infoNode=null) 号数据同步失败原因: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_center_client\target\classes\mapper\DataSyncMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into data_sync(info_id, info_type, info_node, sync_type, sync_status, success_time, fail_time, fail_count, sync_msg)         value(?,?,?,?,?,?,?,?,?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
; Column 'sync_type' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'sync_type' cannot be null
