12:50:35.764 [MQTT Call: cj_node] ERROR com.ntu.node.sync.NodeDataReceiver - CHANGJIANG_BOX_SENSOR表中 10 号数据同步失败....
12:50:45.706 [MQTT Call: cj_node] ERROR com.ntu.node.sync.NodeDataReceiver - CHANGJIANG_BOX_SENSOR表中 10 号数据同步失败....
12:50:56.713 [MQTT Call: cj_node] ERROR com.ntu.node.sync.NodeDataReceiver - CHANGJIANG_BOX_SENSOR表中 10 号数据同步失败....
12:51:07.719 [MQTT Call: cj_node] ERROR com.ntu.node.sync.NodeDataReceiver - CHANGJIANG_BOX_SENSOR表中 10 号数据同步失败....
12:51:18.725 [MQTT Call: cj_node] ERROR com.ntu.node.sync.NodeDataReceiver - CHANGJIANG_BOX_SENSOR表中 10 号数据同步失败....
12:55:59.044 [main] ERROR com.ntu.common.client.EMQTTClient - 已断开连接
12:55:59.089 [main] ERROR org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 8083 was already in use.

Action:

Identify and stop the process that's listening on port 8083 or configure this application to listen on another port.

12:56:09.115 [node1] ERROR com.ntu.node.sync.SendThread - nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: HikariDataSource HikariDataSource (null) has been closed.
### The error may exist in file [C:\Users\Lenovo\Desktop\datasync\datasync_node1_client\target\classes\mapper\DataSynchroMapper.xml]
### The error may involve com.ntu.node.mapper.DataSynchroMapper.querySyncData
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: HikariDataSource HikariDataSource (null) has been closed.
17:45:10.196 [MQTT Call: cj_node] ERROR com.ntu.node.sync.NodeDataReceiver - AREA_SPOT表中 1 号数据同步失败....
17:45:21.204 [MQTT Call: cj_node] ERROR com.ntu.node.sync.NodeDataReceiver - AREA_SPOT表中 1 号数据同步失败....
17:45:32.260 [MQTT Call: cj_node] ERROR com.ntu.node.sync.NodeDataReceiver - AREA_SPOT表中 1 号数据同步失败....
17:45:43.243 [MQTT Call: cj_node] ERROR com.ntu.node.sync.NodeDataReceiver - AREA_SPOT表中 1 号数据同步失败....
17:45:54.339 [MQTT Call: cj_node] ERROR com.ntu.node.sync.NodeDataReceiver - AREA_SPOT表中 1 号数据同步失败....
18:27:19.136 [MQTT Call: cj_node] ERROR com.ntu.node.sync.NodeDataReceiver - AREA_SPOT表中 3 号数据同步失败....
18:27:28.136 [node1] ERROR com.ntu.node.sync.SendThread - 同步数据不存在：DataSynchro(basicinfoid=3, type=S, areaName=null, sa1Status=9, sb1Time=null, sc1Time=Mon May 11 18:27:19 CST 2020, sd1Num=1, se1Time=Mon May 11 18:27:19 CST 2020, sf1Msg=synchronize data failed, sa2Status=null, sb2Time=null, sc2Time=null, sf2Msg=null)
18:29:48.232 [node1] ERROR com.ntu.node.sync.SendThread - 同步数据不存在：DataSynchro(basicinfoid=3, type=S, areaName=null, sa1Status=1, sb1Time=null, sc1Time=Mon May 11 18:27:28 CST 2020, sd1Num=0, se1Time=Mon May 11 18:27:19 CST 2020, sf1Msg=data not found, sa2Status=null, sb2Time=null, sc2Time=null, sf2Msg=null)
